steps:
  # Step 1: Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/avioxus/avioxus-bot", "."]

  # Step 2: Push the Docker image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/avioxus/avioxus-bot"]

  # Step 3: Fetch secrets from Google Secret Manager and deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        # Fetch secrets from Google Secret Manager
        DISCORD_TOKEN=$(gcloud secrets versions access latest --secret="DISCORD_TOKEN")
        DISCORD_PUBLIC_KEY=$(gcloud secrets versions access latest --secret="DISCORD_PUBLIC_KEY")
        CLIENT_ID=$(gcloud secrets versions access latest --secret="CLIENT_ID")
        PERSONAL_HUB_GUILD_ID=$(gcloud secrets versions access latest --secret="PERSONAL_HUB_GUILD_ID")
        DAILY_POSTS_CHANNEL_ID=$(gcloud secrets versions access latest --secret="DAILY_POSTS_CHANNEL_ID")
        STOCK_API_KEY=$(gcloud secrets versions access latest --secret="STOCK_API_KEY")
        CRYPTO_API_KEY=$(gcloud secrets versions access latest --secret="CRYPTO_API_KEY")
        NEWS_API_KEY=$(gcloud secrets versions access latest --secret="NEWS_API_KEY")
        WEATHER_API_KEY=$(gcloud secrets versions access latest --secret="WEATHER_API_KEY")
        WORD_API_KEY=$(gcloud secrets versions access latest --secret="WORD_API_KEY")

        # Deploy the service to Cloud Run with the secrets as environment variables
        gcloud run deploy avioxus-bot \
          --image gcr.io/avioxus/avioxus-bot \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars DISCORD_TOKEN=$$DISCORD_TOKEN,DISCORD_PUBLIC_KEY=$$DISCORD_PUBLIC_KEY,CLIENT_ID=$$CLIENT_ID,PERSONAL_HUB_GUILD_ID=$$PERSONAL_HUB_GUILD_ID,DAILY_POSTS_CHANNEL_ID=$$DAILY_POSTS_CHANNEL_ID,STOCK_API_KEY=$$STOCK_API_KEY,CRYPTO_API_KEY=$$CRYPTO_API_KEY,NEWS_API_KEY=$$NEWS_API_KEY,WEATHER_API_KEY=$$WEATHER_API_KEY,WORD_API_KEY=$$WORD_API_KEY

# Define substitutions (optional, useful for dynamic builds)
substitutions:
  _REGION: "us-central1"

# Timeout for the build process
timeout: "1200s"

# Specify the service account for Cloud Build
serviceAccount: "avioxus-service-account@avioxus.iam.gserviceaccount.com"

# Options for build
options:
  logging: CLOUD_LOGGING_ONLY
